--1
SELECT ENAME AS 사원명,SAL AS 급여,SAL+300 AS 인상된급여 FROM EMP;
--2
SELECT ENAME AS 사원명,SAL AS 급여,SAL*12+100 AS 연간_총_수입 FROM EMP ORDER BY 연간_총_수입 DESC;
--3
SELECT ENAME AS 사원명 , SAL AS 급여 FROM EMP WHERE SAL >2000 ORDER BY SAL DESC;
--4
SELECT ENAME AS 사원명 , DEPTNO AS 부서번호 FROM EMP WHERE EMPNO = 7788;
--5
SELECT ENAME AS 사원명 , SAL AS 급여 FROM EMP
MINUS
SELECT ENAME AS 사원명 ,SAL AS 급여 FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
--6
SELECT ENAME AS 사원명 , JOB AS 담당업무 ,HIREDATE AS 입사일 FROM EMP WHERE HIREDATE BETWEEN TO_DATE('1981-02-20','YYYY-MM-DD') AND TO_DATE('1981-05-01','YYYY-MM-DD');
--7
SELECT ENAME AS 사원명 , DEPTNO AS 부서번호 FROM EMP WHERE DEPTNO IN(20,30) ORDER BY ENAME DESC;
--8
SELECT ENAME AS 사원명 , SAL AS 급여 , DEPTNO AS 부서번호 FROM EMP WHERE SAL BETWEEN 2000 AND 3000 AND DEPTNO IN(20,30)ORDER BY ENAME;
--9
SELECT ENAME AS 사원명 , HIREDATE AS 입사일 FROM EMP WHERE HIREDATE LIKE ('%81%');
--10
SELECT ENAME AS 사원명 , JOB AS 담당업무 FROM EMP WHERE MGR IS NULL;
--11
SELECT ENAME AS 사원명 , SAL AS 급여 , COMM AS 커미션 FROM EMP WHERE COMM IS NOT NULL;
