ALTER SESSION SET "_ORACLE_SCRIPT" =TRUE; -- C##을 안써도됨.
CREATE USER JHTA01 IDENTIFIED BY 1234;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO JHTA01;
DROP USER JHTA01 CASCADE;
GRANT CREATE SESSION TO JHTA01; -- CONNECTION 권한 
GRANT CREATE SESSION, CREATE TABLE, RESOURCE TO JHTA01;  --CREATE TALBE 등등의 권한부여

--ROLE 역할만들기
CREATE ROLE MYROLE01;

--만들어진 역할에 권한부여하기
GRANT CONNECT,RESOURCE,CREATE TABLE,CREATE VIEW,CREATE SYNONYM TO MYROLE01; --SYSTEM 권한

GRANT MYROLE01 TO JHTA01;

SELECT * FROM ALL_USERS;
SELECT * FROM USER_ROLE_PRIVS;

SELECT * FROM JHTA01.TEMP02;