ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER JHTA02 IDENTIFIED BY 1234;
--CONNECT 는 ROLE 이고 CREATE SESSION 권한이 들어가있다.
GRANT CONNECT, RESOURCE , UNLIMITED TABLESPACE TO JHTA02;
--ROLE 은 권한의 묶음이다.